### PR TITLE
configs/*demo*: remove Dropbear as OpenSSH is also selected

### PR DESCRIPTION
**Pull request by tpetazzoni**
Enabling both Dropbear and OpenSSH in the same defconfig does not make
a lot of sense, as they both provide a SSH server and client. Only one
of them will act as a SSH server, as only one of them can listen to
TCP port 22.

Since OpenSSH is more feature-complete and those demo defconfigs
already have lots of other packages, keeping OpenSSH seems the best
choice.

This commit solves a comment made as part of
https://github.com/linux4sam/buildroot-external-microchip/issues/1.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>

### CODE REVIEW

**Review by ldesroches — APPROVED** [review]
Thank you Thomas.

**Comment by ehristev** [comment]
This needs to be ported to the latest version of external.
It was decided that we keep dropbear at some point instead of openssh 
Do not know for sure for next revision .
What do you advise ?

**Comment by ehristev** [comment]
We need both dropbear and openssh on buildroot demos.
Dropbear is more easily used to deploy QT apps with QTcreator for example.
The bad part is that both of them deploy init scripts. 
From my understanding this is a limitation of buildroot: cannot deploy package with/without the init script (to select from somewhere...)
So, if we can fix the init scripts to have just one of them starting automatically, it would be good.
Otherwise we will keep both packets for now.

**Comment by tpetazzoni** [comment]
I don't understand why you need both. QtCreator can be used either with OpenSSH or with Dropbear+gesftpserver, so I'm pretty sure you don't need both.

Also, for the init script issue, you can remove the one you don't need by using a post-build script, but again I'm pretty sure you don't need both OpenSSH and Dropbear.

**Pull request closed without merging**
